#ifndef INTERPRETERFLEXLEXER_H
#define INTERPRETERFLEXLEXER_H

#ifndef YY_DECL
#define YY_DECL \
    yy::InterpreterParser::symbol_type InterpreterFlexLexer::yylex(InterpreterDriver& driver)
#endif

// apparently this causes issues with the preprocessor when processing FlexLexer.h (the output file from Flex)
#undef yyFlexLexer
#include <FlexLexer.h>

#include <InterpreterParser.hpp>

class InterpreterFlexLexer : public yyFlexLexer {

    public:
        // this uses the superclass constructor
        using yyFlexLexer::yyFlexLexer;

        // interface to yylex, definition generated by Flex
        yy::InterpreterParser::symbol_type yylex(InterpreterDriver& driver);
};

#endif